// boltConstants.js

export const ALL_BOLTS_REQUEST = 'ALL_BOLTS_REQUEST';
export const ALL_BOLTS_SUCCESS = 'ALL_BOLTS_SUCCESS';
export const ALL_BOLTS_FAIL = 'ALL_BOLTS_FAIL';

export const BOLT_DETAILS_REQUEST = 'BOLT_DETAILS_REQUEST';
export const BOLT_DETAILS_SUCCESS = 'BOLT_DETAILS_SUCCESS';
export const BOLT_DETAILS_FAIL = 'BOLT_DETAILS_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';