// filterConstants.js

export const SET_SCREW_FILTER_VALUES = 'SET_SCREW_FILTER_VALUES';
export const SET_PLATE_FILTER_VALUES = 'SET_PLATE_FILTER_VALUES';
export const SET_BOLT_FILTER_VALUES = 'SET_BOLT_FILTER_VALUES';
export const SET_FILTER_TYPE = 'SET_FILTER_TYPE';
