// plateConstants.js

export const ALL_PLATES_REQUEST = 'ALL_PLATES_REQUEST';
export const ALL_PLATES_SUCCESS = 'ALL_PLATES_SUCCESS';
export const ALL_PLATES_FAIL = 'ALL_PLATES_FAIL';

export const PLATE_DETAILS_REQUEST = 'PLATE_DETAILS_REQUEST';
export const PLATE_DETAILS_SUCCESS = 'PLATE_DETAILS_SUCCESS';
export const PLATE_DETAILS_FAIL = 'PLATE_DETAILS_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
